name: autorun

on:
  workflow_dispatch:
  schedule:
    # 5分钟运行一次
    - cron: '0/5 * * * *'
    

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check if service is running
      id: check_service
      run: |
        if curl --head --silent --fail https://memos.milaone.app > /dev/null; then #这里改成你的Web服务的地址
          echo "service_status=running" >> $GITHUB_ENV
        else
          echo "service_status=not_running" >> $GITHUB_ENV
        fi

    - name: Run script on remote server if service is not running
      if: env.service_status == 'not_running'
      run: ssh -o StrictHostKeyChecking=no dino@s4.serv00.com "./run.sh" #这里改成你的用户名@你的ssh服务器地址
